float64 gain
geometry_msgs/Point position
float64[5] initial_configuration
string metric_name
---
float64 score
float64 position_error
---
geometry_msgs/Point current_position
float64[5] current_configuration
float64 score
float64 position_error